### ISSUE TITLE
Getting error while executing python3 erfan4lx.py in terminal

### ISSUE THREAD

**Issue by SM113330** [erfan4lx/Telegram-Group-Member-Scraper#1]
Traceback (most recent call last):
  File "erfan4lx.py", line 3, in <module>
    from telethon.sync import TelegramClient
ModuleNotFoundError: No module named 'telethon'

**Comment by erfan4lx** [comment]
Hi

Try this command then run the tool :
python -m pip install telethon

Then you can use the tool, Good luck

**Comment by Life9700** [comment]
erfan4lx is a scamer guys dont send him any money if he ask becouse he scamed me i can show proof he is bluddy scamer
